module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'ant-blue': '#1677FF',
        'ant-purple': '#722ED1',
        'ant-cyan': '#13C2C2',
        'ant-green': '#52C41A',
        'ant-magenta': '#EB2F96',
        'ant-pink': '#EB2F96',
        'ant-red': '#F5222D',
        'ant-orange': '#FA8C16',
        'ant-yellow': '#FADB14',
        'ant-volcano': '#FA541C',
        'ant-geekblue': '#2F54EB',
        'ant-gold': '#FAAD14',
        'ant-lime': '#A0D911',
        'primary': '#04a5df',
        'success': '#52c41a',
        'warning': '#faad14',
        'error': '#ff4d4f',
        'info': '#04a5df',
        'link': '#04a5df',
        'text-base': '#000',
        'bg-base': '#fff',
      },
      fontFamily: {
        'ant': ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'Noto Sans', 'sans-serif', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'],
        'ant-code': ['SFMono-Regular', 'Consolas', 'Liberation Mono', 'Menlo', 'Courier', 'monospace'],
      },
      fontSize: {
        'ant-sm': '12px',
        'ant-lg': '16px',
        'ant-xl': '20px',
        'ant-heading-1': '38px',
        'ant-heading-2': '30px',
        'ant-heading-3': '24px',
        'ant-heading-4': '20px',
        'ant-heading-5': '16px',
      },
      borderRadius: {
        'ant': '6px',
        'ant-xs': '2px',
        'ant-sm': '4px',
        'ant-lg': '8px',
      },
      spacing: {
        'ant-xxs': '4px',
        'ant-xs': '8px',
        'ant-sm': '12px',
        'ant': '16px',
        'ant-md': '20px',
        'ant-lg': '24px',
        'ant-xl': '32px',
        'ant-xxl': '48px',
      },
      height: {
        'ant-control': '32px',
        'ant-control-sm': '24px',
        'ant-control-xs': '16px',
        'ant-control-lg': '40px',
      },
      boxShadow: {
        'ant': '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
        'ant-secondary': '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
        'ant-tertiary': '0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)',
        'ant-card': '0 1px 2px -2px rgba(0, 0, 0, 0.16), 0 3px 6px 0 rgba(0, 0, 0, 0.12), 0 5px 12px 4px rgba(0, 0, 0, 0.09)',
      },
    },
  },
  plugins: [],
}
